/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForTruckersRouteImport } from './routes/for-truckers'
import { Route as ForSuppliersRouteImport } from './routes/for-suppliers'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTruckersRoute = ForTruckersRouteImport.update({
  id: '/for-truckers',
  path: '/for-truckers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSuppliersRoute = ForSuppliersRouteImport.update({
  id: '/for-suppliers',
  path: '/for-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/for-truckers': typeof ForTruckersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/for-truckers': typeof ForTruckersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/for-truckers': typeof ForTruckersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/blog'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-suppliers'
    | '/for-truckers'
    | '/help'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/blog'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-suppliers'
    | '/for-truckers'
    | '/help'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/blog'
    | '/contact'
    | '/download'
    | '/features'
    | '/for-suppliers'
    | '/for-truckers'
    | '/help'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiAssistantRoute: typeof AiAssistantRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForSuppliersRoute: typeof ForSuppliersRoute
  ForTruckersRoute: typeof ForTruckersRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LegalRoute: typeof LegalRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-truckers': {
      id: '/for-truckers'
      path: '/for-truckers'
      fullPath: '/for-truckers'
      preLoaderRoute: typeof ForTruckersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-suppliers': {
      id: '/for-suppliers'
      path: '/for-suppliers'
      fullPath: '/for-suppliers'
      preLoaderRoute: typeof ForSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiAssistantRoute: AiAssistantRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForSuppliersRoute: ForSuppliersRoute,
  ForTruckersRoute: ForTruckersRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LegalRoute: LegalRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
